name: medical_app
description: "Medical Store Management App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2

  # Database
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.4.0+1
  sqflite_common: ^2.5.6
  path: ^1.9.1

  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.5.4
  flutter_pos_printer_platform_image_3: ^1.2.4
  file_picker: ^10.3.10
  excel: ^4.0.6
  share_plus: ^12.0.1
  open_file: ^3.5.11

  # Printing
  bluetooth_print: ^4.3.0
  esc_pos_utils_plus: ^2.0.4
  printing: ^5.14.2
  print_bluetooth_thermal: ^1.1.1
  flutter_usb_printer: ^0.1.0+1   # ✅ FIXED
  pdf: ^3.12.0
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/Roboto/static/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/static/Roboto_Condensed-Italic.ttf
        - asset: assets/fonts/Roboto/static/Roboto_Condensed-Medium.ttf
          weight: 700